### ISSUE TITLE
Cannot run examples

### ISSUE THREAD

**Issue by Binsoma** [pedro-vicente/lib_netsockets#1]
Hi Pedro,

I have followed all the steps to download and build lib_netsockets. The problem I'm facing is I cannot get the examples to run. Also cannot locate the example executables. Could you provide a step by step on how to use lib_netsockets. Thanks.

**Comment by pedro-vicente** [comment]
to build

```
mkdir build
cd build
cmake..
```

On Windows this generates a Visual Studio solution lib_netsockets.sln. Open it and build, it includes the examples

On UNIX, do 

`make`

it will build all the examples

**Comment by Binsoma** [comment]
I have done that. The problem, there are no executables/can't find them

**Comment by Binsoma** [comment]
inside examples directory. I have .cc files only.

**Comment by pedro-vicente** [comment]
ok, please post the output of 

```
cmake ..
make
```

**Comment by Binsoma** [comment]
cmake ..
-- Found /openssl/ssl.h header file at: /usr/include
-- Found OpenSSL library at: /usr/lib/i386-linux-gnu/libssl.so
-- Found CRYPTO library at: /usr/lib/i386-linux-gnu/libcrypto.so
-- Building SSL TCP example
-- Configuring done
-- Generating done
-- Build files have been written to: ../lib_netsockets/build

make
[ 32%] Building CXX object CMakeFiles/sqlite_server.dir/examples/sqlite_server.cc.o
lib_netsockets/examples/sqlite_server.cc: In function ‘int main(int, char**)’:
../lib_netsockets/examples/sqlite_server.cc:204:24:
 error: ‘strlen’ was not declared in this scope
     strlen(json.c_str()), json.c_str());
                        ^

**Comment by pedro-vicente** [comment]
do 
`git pull`
and try again, there was a missing header file

you should have these example programs


```
ftp_client   http_coin http_server  json_server  sqlite_server  tcp_client
http_client  json_client  ssl_client     tcp_server
```

**Comment by Binsoma** [comment]
I have managed to get it working! All examples are there.
 Many thanks Pedro.
 Happy new year.
