### ISSUE TITLE
Error in the inmake

### ISSUE THREAD

**Issue by carter3rix** [pedro-vicente/lib_netsockets#3]
`Had this error
`Scanning dependencies of target https_coin
[  1%] Building CXX object CMakeFiles/https_coin.dir/src/openssl_socket.cc.o
/mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.cc: In function ‘int hostname_to_ip(const char*, char*)’:
/mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.cc:18:3: error: ‘memset’ was not declared in this scope
   memset(&hints, 0, sizeof hints);
   ^~~~~~
/mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.cc:18:3: note: suggested alternative: ‘wmemset’
   memset(&hints, 0, sizeof hints);
   ^~~~~~
   wmemset
/mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.cc:31:5: error: ‘strcpy’ was not declared in this scope
     strcpy(ip, inet_ntoa(h->sin_addr));
     ^~~~~~
/mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.cc:31:5: note: suggested alternative: ‘wcpcpy’
     strcpy(ip, inet_ntoa(h->sin_addr));
     ^~~~~~
     wcpcpy
/mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.cc: In member function ‘int ssl_socket_t::open(const char*)’:
/mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.cc:102:3: error: ‘memset’ was not declared in this scope
   memset(&server_addr, 0, sizeof(server_addr));
   ^~~~~~
/mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.cc:102:3: note: suggested alternative: ‘wmemset’
   memset(&server_addr, 0, sizeof(server_addr));
   ^~~~~~
   wmemset
/mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.cc:116:52: warning: ‘const SSL_METHOD* TLSv1_2_client_method()’ is deprecated [-Wdeprecated-declarations]
   SSL_CTX *ctx = SSL_CTX_new(TLSv1_2_client_method());
                                                    ^
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from /mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.hh:19,
                 from /mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.cc:1:
/usr/include/openssl/ssl.h:1638:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_client_method(void)) /* TLSv1.2 */
 ^
/mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.cc: In member function ‘int ssl_socket_t::send(const char*)’:
/mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.cc:138:35: error: ‘strlen’ was not declared in this scope
   int len = SSL_write(m_ssl, buf, strlen(buf));
                                   ^~~~~~
/mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.cc:138:35: note: suggested alternative: ‘mbrlen’
   int len = SSL_write(m_ssl, buf, strlen(buf));
                                   ^~~~~~
                                   mbrlen
CMakeFiles/https_coin.dir/build.make:62: recipe for target 'CMakeFiles/https_coin.dir/src/openssl_socket.cc.o' failed
make[2]: *** [CMakeFiles/https_coin.dir/src/openssl_socket.cc.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/https_coin.dir/all' failed
make[1]: *** [CMakeFiles/https_coin.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2``

**Comment by carter3rix** [comment]
Hello i post the error i had above so please can you help me out... i don't what going on in openssl
/mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.cc: In function ‘int hostname_to_ip(const char*, char*)’:
/mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.cc:18:3: error: ‘memset’ was not declared in this scope
memset(&hints, 0, sizeof hints);
^~~~~~
/mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.cc:18:3: note: suggested alternative: ‘wmemset’
memset(&hints, 0, sizeof hints);
^~~~~~
wmemset
/mnt/c/HAPPS/CTHINGS/CLIB/lib_netsockets/src/openssl_socket.cc:31:5: error: ‘strcpy’ was not declared in this scope
strcpy(ip, inet_ntoa(h->sin_addr));

**Comment by pedro-vicente** [comment]
try adding 

#include <string.h>

**Comment by carter3rix** [comment]
Ok
