### ISSUE TITLE
connect error: bad file descriptor

### ISSUE THREAD

**Issue by kchmie** [pedro-vicente/lib_netsockets#4]
Hi, im getting this message when trying to connect to server.

My host server function:
`socket_t hostServer()
{
	tcp_server_t server(7788);
	socket_t socket = server.accept_client();
	return socket;
}`

My connect to server function:
`tcp_client_t openConnection(char* host)
{
	tcp_client_t client(host, 7788);
	client.open();
	return client;
}`

Is there any solution for this?

**Comment by kchmie** [comment]
Ps. i never closed client connection and opened it few times, may this be it?

**Comment by pedro-vicente** [comment]
yes, you have to close the client socket for the server to return, otherwise you will be in a endless loop;

simple client

```
 char buf[10];
  sprintf(buf, "12345");
  tcp_client_t client("127.0.0.1", 2000);
  //create socket and open connection
  client.open();
  client.write_all(buf, strlen(buf));
  std::cout << "client sent " << strlen(buf) << " bytes: " << buf;
  //close connection
  client.close_socket();
```

server


```
char buf[255];
  tcp_server_t server(2000);
  while (true)
  {
    socket_t socket = server.accept_client();
    int recv_size = socket.read_all(buf, sizeof(buf));
    std::string str(buf, recv_size);
    std::cout << "server received " << recv_size << " bytes: " << str;
    socket.close_socket();
  }
  server.close_socket();
```
